# Full reference at http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}

configuration: Release

before_build:
- nuget restore AzureJobs.sln

build_script:
- ps: if($env:APPVEYOR_REPO_BRANCH -ne "release"){C:\projects\azurejobs\build-main.ps1} else {C:\projects\azurejobs\build-main.ps1 -publishToProd}

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT
  SiteExtensionsNuGetApiKey:
    secure: O/+/C4Pw22PwwM6arJ2x556zaO26Un5gYknMDo33zOJNUDbj1qfKnPpTNSqUneUc

test:
  assemblies:
  - OutputRoot\obj\**\*test*.dll
  - todelete

artifacts:
- path: OutputRoot\**\*.nupkg

nuget:
  account_feed: true
  project_feed: true